import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Portfolio Builder",
  description: "Portfolio Builder Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        {children}
      </body>
    </html>
  );
}
